security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|react)/
            security: false

        login:
            pattern: ^/authentication/token
            stateless: true
            json_login:
                check_path: authentication_token
                username_path: login
                password_path: password
            login_throttling:
                max_attempts: 5
                interval: '5 minutes'

        email_contact:
            pattern: ^/email/contact
            stateless: true

        api_articles_editor:
            pattern: ^/api/articles/editor.*
            stateless: true
            provider: app_user_provider
            jwt: ~

        api_me:
            pattern: ^/api/me
            stateless: true
            provider: app_user_provider
            jwt: ~

        api_root:
            pattern: ^/api$
            stateless: true
            provider: app_user_provider
            jwt: ~

        public_api:
            pattern: ^/api
            methods: [GET]
            stateless: true

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/authentication, roles: PUBLIC_ACCESS }
        - { path: ^/email/contact, roles: PUBLIC_ACCESS }
        - { path: ^/api$, roles: ROLE_EDITOR }
        - { path: ^/api, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api, roles: ROLE_EDITOR }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
